
CREATE DATABASE PHARMEASE;
USE PHARMEASE;

CREATE TABLE DOCTOR(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    LICENSE_NO VARCHAR(255) NOT NULL
);

CREATE TABLE PATIENT(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    PHONE_NO VARCHAR(255) NOT NULL
);

CREATE TABLE PHARM(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    REGISTRATION_NO VARCHAR(255) NOT NULL
);

CREATE TABLE Prescription(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    URI VARCHAR(255) NOT NULL
);

CREATE TABLE SUBCRIPTION_REQUEST(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    REQUESTER_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STATUS INT,
    USER_TYPE VARCHAR(255)
);

CREATE TABLE AUTH(
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_ID BIGINT NOT NULL,
    USER_TYPE VARCHAR(50) NOT NULL
);

